#Database Setup for MySQL
spring.application.name=loginapp
server.port=8082
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.name=myApp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#Security Config
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

#File Size Manage
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

#Cookie Path Set 
server.servlet.session.cookie.path=/

#JWT Secret Key
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#Groq API for Category Detection 
groq.api.key=${GROQ_API_KEY}

#Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}