#Database Setup for MySQL
spring.application.name=loginapp
server.port=8082
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.name=myApp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#Security Config
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

#File Size Manage
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

#Cookie Path Set 
server.servlet.session.cookie.path=/
app.secure-cookie=${SECURE_COOKIE:false}

#JWT Secret Key
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#Groq API for Category Detection 
groq.api.key=${GROQ_API_KEY}

#Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#OTP validity period in minutes
app.otp.expiry-minutes=10

#Redis In-Memory Database Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}